baseURL = "https://docs.casa/"
languageCode = "ja-jp"
title = "Docs Casa"
disablePathToLower = true
enableGitInfo = false
theme = "book"
DefaultContentLanguage = "jp"

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1
